### ISSUE TITLE
Profile creation missing `disable-sgn` flag in v1.5.32

### ISSUE THREAD

**Issue by mttaggart** [BishopFox/sliver#1055]
**Describe the bug**
When running `profiles new`, the client crashes, missing a registered `disable-sgn` flag, which seems to have been added, according to the changenotes.

**To Reproduce**
1. Run `profiles new -f exe --mtls 127.0.0.1:8888 test_mtls`
2. Observe the following error

```
panic: missing flag value: flag 'disable-sgn' not registered

goroutine 1 [running]:
github.com/desertbit/grumble.FlagMap.Bool(0x1769b7a?, {0x1783234, 0xb})
        github.com/desertbit/grumble@v1.1.1/flagmap.go:72 +0x105
github.com/bishopfox/sliver/client/command/generate.parseCompileFlags(0xc0005f2080, 0xc00009a320)
        github.com/bishopfox/sliver/client/command/generate/generate.go:349 +0x110d
github.com/bishopfox/sliver/client/command/generate.ProfilesNewCmd(0xc0005f2080, 0xc00009a320)
        github.com/bishopfox/sliver/client/command/generate/profiles-new.go:31 +0x53
github.com/bishopfox/sliver/client/command.BindCommands.func148(0xc0005f0060?)
        github.com/bishopfox/sliver/client/command/commands.go:1583 +0x45
github.com/desertbit/grumble.(*App).RunCommand(0xc000034540, {0xc000410080?, 0x3a?, 0x1bf6548?})
        github.com/desertbit/grumble@v1.1.1/app.go:273 +0x19f
github.com/desertbit/grumble.(*App).runShell(0xc000034540)
        github.com/desertbit/grumble@v1.1.1/app.go:485 +0x4e6
github.com/desertbit/grumble.(*App).RunWithReadline(0xc000034540, 0xc0003934d0)
        github.com/desertbit/grumble@v1.1.1/app.go:407 +0x570
github.com/desertbit/grumble.(*App).Run(0xc000034540)
        github.com/desertbit/grumble@v1.1.1/app.go:291 +0x125
github.com/bishopfox/sliver/client/console.Start({0x1c65038?, 0xc0000402d0}, 0x1a4e798, 0x1a4e0f8, 0x0)
        github.com/bishopfox/sliver/client/console/console.go:145 +0x577
github.com/bishopfox/sliver/client/cli.StartClientConsole()
        github.com/bishopfox/sliver/client/cli/cli.go:100 +0x1a6
github.com/bishopfox/sliver/client/cli.glob..func1(0x262e6e0?, {0x175b4fa?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/client/cli/cli.go:74 +0x73
github.com/spf13/cobra.(*Command).execute(0x262e6e0, {0xc000118210, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x262e6e0)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/bishopfox/sliver/client/cli.Execute()
        github.com/bishopfox/sliver/client/cli/cli.go:105 +0x25
main.main()
        github.com/bishopfox/sliver/client/main.go:43 +0x17
```

**Expected behavior**
The profile should be saved without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/6811816/210495745-803ce1f9-9140-436e-b295-c2cad44ef3fd.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux

**Comment by necroph0s** [comment]
This is my doing, I'll fix this in the morning.
