### ISSUE TITLE
Stacktrace from Panic after running sliver-server

### ISSUE THREAD

**Issue by rockabillycat666** [BishopFox/sliver#1318]
**Describe the bug**
After installing Sliver with the script:   curl https://sliver.sh/install|sudo bash   ran sliver-server

got the following error:
```
└─# ./sliver-server      
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
	github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc0003f08c0})
	runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
	github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
	github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc000052290, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
	github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
	github.com/bishopfox/sliver/server/main.go:43 +0x17
```

**To Reproduce**
1. Installed Sliver with " curl https://sliver.sh/install|sudo bash"

```
─$ curl https://sliver.sh/install|sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6127  100  6127    0     0  14378      0 --:--:-- --:--:-- --:--:-- 14382
Running from /root
gpg: key 7DF912404449039C: "Sliver <sliver@bishopfox.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.40/sliver-client_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.40/sliver-client_linux.sig
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.40/sliver-server_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.40/sliver-server_linux.sig
Verifying signatures ...
gpg: Signature made Tue 20 Jun 2023 02:32:22 PM EDT
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C
gpg: Signature made Tue 20 Jun 2023 02:32:22 PM EDT
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C

Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
'/root/sliver-client_linux' -> '/usr/local/bin/sliver-client'
ln: failed to create symbolic link '/usr/local/bin/sliver': File exists
```
..'
2.  Tried running sliver-server:

```
└─# ./sliver-server      
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
	github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc0003f08c0})
	runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
	github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
	github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc000052290, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
	github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
	github.com/bishopfox/sliver/server/main.go:43 +0x17
```
Also, somehow after installing it, I am not seeing the sliver-server_linux file. 

**Expected behavior**
Expected sliver-server to run. 

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Version Linux kali 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux

**Comment by rockabillycat666** [comment]
was able to fix it by completly remove everything related to sliver. 

remove .sliver and .sliver-client and everything sliver related on the /root folder. 

Sorry about openning this thread.

**Comment by moloch--** [comment]
Yea, unfortunately v1.5.40 isn't backwards compatible due to security fixes so you need to clear out the home directories.

**Comment by obitori** [comment]
The same solution works for 1.5.42.
