### ISSUE TITLE
Bug: Running the Sliver server as root crashes.

### ISSUE THREAD

**Issue by U53RW4R3** [BishopFox/sliver#1331]
**Describe the bug**

When the `sliver-server` executed as `root` or as a service. It crashed. However, if you run as a normal user it works perfectly fine.

**To Reproduce**

```
# ./sliver-server
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
        github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc0000b28c0})
        runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
        github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc0000aa270, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
        github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
        github.com/bishopfox/sliver/server/main.go:43 +0x17

$ ./sliver-server_linux

Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
[*] Loaded 14 aliases from disk
[*] Loaded 7 extension(s) from disk

.------..------..------..------..------..------.
|S.--. ||L.--. ||I.--. ||V.--. ||E.--. ||R.--. |
| :/\: || :/\: || (\/) || :(): || (\/) || :(): |
| :\/: || (__) || :\/: || ()() || :\/: || ()() |
| '--'S|| '--'L|| '--'I|| '--'V|| '--'E|| '--'R|
`------'`------'`------'`------'`------'`------'

All hackers gain exalted
[*] Server v1.5.40 - c17c37857e54f0fa202c01cbd00a99a85f5f9f49
[*] Welcome to the sliver shell, please type 'help' for options

[server] sliver > exit
```

**Expected behavior**

It should run normally in the background with listening port 31337.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2023.2
 - Version  v1.5.40

**Comment by moloch--** [comment]
v1.5.40 isn't backwards compatible, do a quick `rm -rf /root/.sliver` and it should start working again.
