### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by 05t3** [BishopFox/sliver#1361]
Hey Team, Why do I run into this issue when running `sliver-server` on my Kali.

```bash
➜  sliver-server 
panic: runtime error: index out of range [1] with length 1

goroutine 96 [running]:
github.com/bishopfox/sliver/server/rpc.(*Server).GetVersion(0xc25b62e409?, {0x19551b2?, 0x6?}, 0x196775a?)
	github.com/bishopfox/sliver/server/rpc/rpc.go:90 +0x165
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler.func1({0x9629490, 0xc00034e030}, {0x17d7720?, 0xc000345020})
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:2113 +0x7b
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.PayloadUnaryServerInterceptor.func1({0x9629490, 0xc00034e030}, {0x17d7720, 0xc000345020}, 0x0?, 0xc0004c1998)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/payload_interceptors.go:29 +0x17d
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc00034e030}, {0x17d7720, 0xc000345020})
	google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x9629490, 0xc000345f20}, {0x17d7720, 0xc000345020}, 0xc0001eb440, 0xc000560cc0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0x102
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc000345f20}, {0x17d7720, 0xc000345020})
	google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1({0x9629490?, 0xc000345080?}, {0x17d7720, 0xc000345020}, 0xc0001eb440, 0xc000560c80)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/tags/interceptors.go:23 +0xa6
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc000345080}, {0x17d7720, 0xc000345020})
	google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/bishopfox/sliver/server/transport.auditLogUnaryServerInterceptor.func1({0x9629490, 0xc000345080}, {0x17d7720, 0xc000345020}, 0xc0001eb440, 0xc000560bc0)
	github.com/bishopfox/sliver/server/transport/middleware.go:223 +0x395
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc000345080}, {0x17d7720, 0xc000345020})
	google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1({0x9629490, 0xc000344ff0}, {0x17d7720, 0xc000345020}, 0xc0001eb440, 0xc000560b80)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:47 +0xba
google.golang.org/grpc.chainUnaryInterceptors.func1({0x9629490, 0xc000344ff0}, {0x17d7720, 0xc000345020}, 0xc000078a20?, 0x173d400?)
	google.golang.org/grpc@v1.54.0/server.go:1155 +0x8f
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler({0x1946a20?, 0xa27bad0}, {0x9629490, 0xc000344ff0}, 0xc00015eb60, 0xc000245660)
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:2115 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c63c0, {0x9632f80, 0xc000431ba0}, 0xc000500360, 0xc00023cb40, 0xa1a7a60, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0002c63c0, {0x9632f80, 0xc000431ba0}, 0xc000500360, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
```

This issue started after i upgraded my kali

**Comment by sohelahmed786** [comment]
I"m also facing same issue on may kali linux arm 64 bit ..

**Comment by RafBishopFox** [comment]
Duplicated in #1362
