### ISSUE TITLE
sliver-server: stacktrace from panic:  goroutine 1 [running]

### ISSUE THREAD

**Issue by trueToastedCode** [BishopFox/sliver#1384]
**Describe the bug**
Trying to start the server, but it fails with errors I do not understand.

**To Reproduce**
1. `sliver-server`

**Output**
```
┌──(parallels㉿kali-linux-2022-2)-[~]
└─$ sliver-server                             

Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/bishopfox/sliver/server/cli.glob..func4.1()
        github.com/bishopfox/sliver/server/cli/cli.go:119 +0x64
panic({0x1585bc0, 0x401bc7f220})
        runtime/panic.go:884 +0x1f4
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
        github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xdc
github.com/bishopfox/sliver/server/cli.glob..func4(0x9c68f00?, {0x17d677a?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/server/cli/cli.go:127 +0x74
github.com/spf13/cobra.(*Command).execute(0x9c68f00, {0x400004e2a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x9c68f00)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
        github.com/bishopfox/sliver/server/cli/cli.go:145 +0x24
main.main()
        github.com/bishopfox/sliver/server/main.go:43 +0x1c
```

**Desktop:**
 - OS: `Linux kali-linux-2022-2 5.18.0-kali5-arm64 #1 SMP Debian 5.18.5-1kali5 (2022-07-04) aarch64 GNU/Linux`
 ```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```
 - Version: `v1.5.47`

**Additional context**
Since I am using arm64, I've compiled the project using these commands, instead of using the "Linux One Liner":
- `git clone https://github.com/BishopFox/sliver.git`
- `cd sliver`
- `git checkout tags/v1.5.47`
- `make`

- go version: `1.20.7 linux/arm64`

**Comment by trueToastedCode** [comment]
Ok, I've used the head of the repository instead of checking out at `tags/v1.5.47`. Now I am finally inside the sliver's server menu 🎉 Not sure if further errors will occur
