### ISSUE TITLE
Panic when trying to assume a session that doesn't exist

### ISSUE THREAD

**Issue by C-Sto** [BishopFox/sliver#170]
**Describe the bug**
Index out of range on session selection

**To Reproduce**
1. type 'sessions -i 2' when session 2 isn't a real thing

**Expected behavior**
nice message saying 'u r dumb, session 2 doesnt exist'

**Screenshots**
```
All hackers gain skulk
[*] v0.0.6 - 23cc4206acd841b030ef62d1e80d6839478dfb6a
[*] Welcome to the sliver shell, please type 'help' for options

sliver > sessions -i 2

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/bishopfox/sliver/client/command.sessions(0xc0003672c0, 0xc00019fa80)
	/Users/moloch/go/src/github.com/bishopfox/sliver/client/command/sessions.go:43 +0x544
github.com/bishopfox/sliver/client/command.BindCommands.func13(0xc0003672c0, 0xc0003672c0, 0x0)
	/Users/moloch/go/src/github.com/bishopfox/sliver/client/command/bind-commands.go:178 +0x8e
github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble.(*App).RunCommand(0xc00035e0c0, 0xc0003847c0, 0x3, 0x4, 0x4, 0x0)
	/Users/moloch/go/src/github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble/app.go:209 +0x176
github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble.(*App).runShell(0xc00035e0c0, 0xc000380030, 0x0)
	/Users/moloch/go/src/github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble/app.go:394 +0x5fc
github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble.(*App).Run(0xc00035e0c0, 0x0, 0x0)
	/Users/moloch/go/src/github.com/bishopfox/sliver/vendor/github.com/desertbit/grumble/app.go:330 +0x51f
github.com/bishopfox/sliver/client/console.Start(0xc00013e000, 0x14ec1c8, 0xc00013e000, 0x0)
	/Users/moloch/go/src/github.com/bishopfox/sliver/client/console/console.go:94 +0x389
github.com/bishopfox/sliver/client/console.StartClientConsole(0xc000000018, 0x14ece20)
	/Users/moloch/go/src/github.com/bishopfox/sliver/client/console/console-client.go:53 +0x3ba
main.main()
	/Users/moloch/go/src/github.com/bishopfox/sliver/client/main.go:60 +0x189
```

**Comment by rkervella** [comment]
Care to test with a more recent version? 0.0.6 is old as fuck ...

**Comment by C-Sto** [comment]
I am very stupid
