### ISSUE TITLE
Crash on namedpipe pivot

### ISSUE THREAD

**Issue by h4ng3r** [BishopFox/sliver#176]
**Describe the bug**
Pivots using named pipes crash if the server dies.

**To Reproduce**
1. crash the server
2. stop the sliver using the named pipe connection (kill it by ctrl-c / via task manager)
3. the pivot will crash

**Additional context**
```
020/04/21 07:02:45 pivots.go:84: Named Pipe error (read msg-length): EOF
2020/04/21 07:02:45 handlers_windows.go:334: EOF
2020/04/21 07:02:45 handlers_windows.go:312: Cleaning up for pivot %d 3379005329
panic: send on closed channel
goroutine 34 [running]:
github.com/bishopfox/sliver/sliver/handlers.nampedPipeConnectionHandler.func1(0xc0c9678791, 0xc000018bd0, 0xc000038240)
        github.com/bishopfox/sliver/sliver/handlers/handlers_windows.go:324 +0x1b6
github.com/bishopfox/sliver/sliver/handlers.nampedPipeConnectionHandler(0xc000018bd0, 0xc000038240, 0xc9678791)
        github.com/bishopfox/sliver/sliver/handlers/handlers_windows.go:336 +0x38e
created by github.com/bishopfox/sliver/sliver/handlers.nampedPipeAcceptNewConnection
        github.com/bishopfox/sliver/sliver/handlers/handlers_windows.go:304 +0x31a
```

**Comment by rkervella** [comment]
Hasn't this one been fixed?

**Comment by h4ng3r** [comment]
I think so.

**Comment by rkervella** [comment]
Closing. We'll reopen if the issues reoccurs.
