### ISSUE TITLE
Unable to install  Sliver

### ISSUE THREAD

**Issue by KR45** [BishopFox/sliver#1821]
I am using Kali Linux arm64  trying to install via curl  , but getting below error can anybody help ?

```
Unpacking assets ...
runtime: lfstack.push invalid packing: node=0xffff91fc9880 cnt=0x1 packed=0xffff91fc98800001 -> node=0xffffffff91fc9880
fatal error: lfstack.push

runtime stack:
runtime.throw({0x1a5936b?, 0x10000000a4c0500?})
	runtime/panic.go:1047 +0x5d fp=0xffff93800188 sp=0xffff93800158 pc=0x43707d
runtime.(*lfstack).push(0x2?, 0xffff93800238?)
	runtime/lfstack.go:29 +0x125 fp=0xffff938001c8 sp=0xffff93800188 pc=0x40d905
runtime.(*spanSetBlockAlloc).free(...)
	runtime/mspanset.go:322
runtime.(*spanSet).reset(0xa563330)
	runtime/mspanset.go:264 +0x87 fp=0xffff938001f8 sp=0xffff938001c8 pc=0x431aa7
runtime.finishsweep_m()
	runtime/mgcsweep.go:260 +0x9c fp=0xffff93800238 sp=0xffff938001f8 pc=0x425e1c
runtime.gcStart.func1()
	runtime/mgc.go:668 +0x17 fp=0xffff93800248 sp=0xffff93800238 pc=0x4629d7
runtime.systemstack()
	runtime/asm_amd64.s:496 +0x49 fp=0xffff93800250 sp=0xffff93800248 pc=0x467b89

goroutine 1 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:463 fp=0xc0003d7818 sp=0xc0003d7810 pc=0x467b20
runtime.gcStart({0xa?, 0x434a000?, 0x40f601?})
	runtime/mgc.go:667 +0x319 fp=0xc0003d78a0 sp=0xc0003d7818 pc=0x41b919
runtime.mallocgc(0x434a000, 0x0, 0x0)
	runtime/malloc.go:1172 +0x777 fp=0xc0003d7908 sp=0xc0003d78a0 pc=0x40f7b7
runtime.rawbyteslice(0x4348dbc)
	runtime/string.go:274 +0xea fp=0xc0003d7958 sp=0xc0003d7908 pc=0x4531ca
runtime.stringtoslicebyte(0x15?, {0x5386a80, 0x4348dbc})
	runtime/string.go:172 +0x4b fp=0xc0003d7998 sp=0xc0003d7958 pc=0x452beb
embed.FS.ReadFile({0xc0003d7ba8?}, {0xc0000569a8, 0x15})
	embed/embed.go:339 +0x4e fp=0xc0003d79c8 sp=0xc0003d7998 pc=0x584b4e
github.com/bishopfox/sliver/server/assets.setupGo({0xc000059f30, 0xd})
	github.com/bishopfox/sliver/server/assets/assets.go:183 +0x392 fp=0xc0003d7c48 sp=0xc0003d79c8 pc=0x9dfa52
github.com/bishopfox/sliver/server/assets.Setup(0x1, 0x1)
	github.com/bishopfox/sliver/server/assets/assets.go:116 +0x174 fp=0xc0003d7cd0 sp=0xc0003d7c48 pc=0x9df5f4
github.com/bishopfox/sliver/server/cli.glob..func7(0xa48a580?, {0x1a24587?, 0x1?, 0x1?})
	github.com/bishopfox/sliver/server/cli/unpack.go:40 +0xa8 fp=0xc0003d7d38 sp=0xc0003d7cd0 pc=0x15038e8
github.com/spf13/cobra.(*Command).execute(0xa48a580, {0xc0002aff70, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847 fp=0xc0003d7e70 sp=0xc0003d7d38 pc=0xea7387
github.com/spf13/cobra.(*Command).ExecuteC(0xa489ce0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc0003d7f28 sp=0xc0003d7e70 pc=0xea7c1d
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
	github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25 fp=0xc0003d7f70 sp=0xc0003d7f28 pc=0x1502bc5
main.main()
	github.com/bishopfox/sliver/server/main.go:43 +0x17 fp=0xc0003d7f80 sp=0xc0003d7f70 pc=0x15040b7
runtime.main()
	runtime/proc.go:250 +0x207 fp=0xc0003d7fe0 sp=0xc0003d7f80 pc=0x4399a7
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0003d7fe8 sp=0xc0003d7fe0 pc=0x469d41

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000076fb0 sp=0xc000076f90 pc=0x439dd6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.forcegchelper()
	runtime/proc.go:305 +0xb0 fp=0xc000076fe0 sp=0xc000076fb0 pc=0x439c10
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x469d41
created by runtime.init.6
	runtime/proc.go:293 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000072780 sp=0xc000072760 pc=0x439dd6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:319 +0xde fp=0xc0000727c8 sp=0xc000072780 pc=0x425f7e
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc0000727e0 sp=0xc0000727c8 pc=0x41b1e6
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x469d41
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc0000b6000?, 0x9895b00?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000072f70 sp=0xc000072f50 pc=0x439dd6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.(*scavengerState).park(0xa53a660)
	runtime/mgcscavenge.go:400 +0x53 fp=0xc000072fa0 sp=0xc000072f70 pc=0x423e53
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:633 +0x65 fp=0xc000072fc8 sp=0xc000072fa0 pc=0x424445
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc000072fe0 sp=0xc000072fc8 pc=0x41b186
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x469d41
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 34 [finalizer wait]:
runtime.gopark(0x1a0?, 0xa53b4c0?, 0xa0?, 0x41?, 0xc000076770?)
	runtime/proc.go:381 +0xd6 fp=0xc000076628 sp=0xc000076608 pc=0x439dd6
runtime.runfinq()
	runtime/mfinal.go:193 +0x107 fp=0xc0000767e0 sp=0xc000076628 pc=0x41a227
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x469d41
created by runtime.createfing
	runtime/mfinal.go:163 +0x45

goroutine 35 [select]:
runtime.gopark(0xc0002fa788?, 0x2?, 0xa8?, 0xf7?, 0xc0002fa784?)
	runtime/proc.go:381 +0xd6 fp=0xc0002fa610 sp=0xc0002fa5f0 pc=0x439dd6
runtime.selectgo(0xc0002fa788, 0xc0002fa780, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x7be fp=0xc0002fa750 sp=0xc0002fa610 pc=0x449a9e
database/sql.(*DB).connectionOpener(0xc0002da8f0, {0x98b7f88, 0xc0002c0cd0})
	database/sql/sql.go:1218 +0x8d fp=0xc0002fa7b8 sp=0xc0002fa750 pc=0xa03fad
database/sql.OpenDB.func1()
	database/sql/sql.go:791 +0x2e fp=0xc0002fa7e0 sp=0xc0002fa7b8 pc=0xa0232e
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0002fa7e8 sp=0xc0002fa7e0 pc=0x469d41
created by database/sql.OpenDB
	database/sql/sql.go:791 +0x18d

goroutine 36 [select]:
runtime.gopark(0xc0002faf90?, 0x2?, 0x0?, 0x0?, 0xc0002faf74?)
	runtime/proc.go:381 +0xd6 fp=0xc0002fade8 sp=0xc0002fadc8 pc=0x439dd6
runtime.selectgo(0xc0002faf90, 0xc0002faf70, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x7be fp=0xc0002faf28 sp=0xc0002fade8 pc=0x449a9e
database/sql.(*DB).connectionCleaner(0xc0002da8f0, 0x0?)
	database/sql/sql.go:1061 +0xa7 fp=0xc0002fafc0 sp=0xc0002faf28 pc=0xa03447
database/sql.(*DB).startCleanerLocked.func1()
	database/sql/sql.go:1048 +0x2a fp=0xc0002fafe0 sp=0xc0002fafc0 pc=0xa0336a
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0002fafe8 sp=0xc0002fafe0 pc=0x469d41
created by database/sql.(*DB).startCleanerLocked
	database/sql/sql.go:1048 +0x105

goroutine 3 [select]:
runtime.gopark(0xc000077618?, 0x4?, 0x0?, 0x0?, 0xc0000775d0?)
	runtime/proc.go:381 +0xd6 fp=0xc000484c58 sp=0xc000484c38 pc=0x439dd6
runtime.selectgo(0xc000484e18, 0xc0000775c8, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x7be fp=0xc000484d98 sp=0xc000484c58 pc=0x449a9e
github.com/bishopfox/sliver/server/core.(*eventBroker).Start(0xc000052570)
	github.com/bishopfox/sliver/server/core/events.go:56 +0x169 fp=0xc000484fc8 sp=0xc000484d98 pc=0xe34029
github.com/bishopfox/sliver/server/core.newBroker.func1()
	github.com/bishopfox/sliver/server/core/events.go:105 +0x26 fp=0xc000484fe0 sp=0xc000484fc8 pc=0xe343c6
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000484fe8 sp=0xc000484fe0 pc=0x469d41
created by github.com/bishopfox/sliver/server/core.newBroker
	github.com/bishopfox/sliver/server/core/events.go:105 +0x150

goroutine 4 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000077f50 sp=0xc000077f30 pc=0x439dd6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1275 +0xf1 fp=0xc000077fe0 sp=0xc000077f50 pc=0x41cf51
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x469d41
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x1257393ec3d?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000078750 sp=0xc000078730 pc=0x439dd6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1275 +0xf1 fp=0xc0000787e0 sp=0xc000078750 pc=0x41cf51
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x469d41
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x12573a6529e?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000073750 sp=0xc000073730 pc=0x439dd6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1275 +0xf1 fp=0xc0000737e0 sp=0xc000073750 pc=0x41cf51
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x469d41
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1199 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x96d4d88?, 0xc00005aa20?, 0x1a?, 0x14?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc0002fb750 sp=0xc0002fb730 pc=0x439dd6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1275 +0xf1 fp=0xc0002fb7e0 sp=0xc0002fb750 pc=0x41cf51
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0002fb7e8 sp=0xc0002fb7e0 pc=0x469d41
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1199 +0x25
```
I recently faced this error apt install also not working

**Comment by moloch--** [comment]
You'll need to compile from source to get the Linux/ARM version working.

**Comment by KR45** [comment]
I tried once compiling it goes smooth but now i am getting this 
```
$sliver                          
Connecting to 0.0.0.0:31337 ...
Connection to server failed context deadline exceeded   
```
