### ISSUE TITLE
cannot run armory command

### ISSUE THREAD

**Issue by homelab192** [BishopFox/sliver#1826]
[*] Fetching 1 armory index(es) ... done!
[*] Fetching package information ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xfba0a7]

goroutine 231 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, {0xc0013c2120, 0x5c}, 0xc00114eab1?)
        github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x167
github.com/bishopfox/sliver/client/command/armory.GithubArmoryPackageParser(0x17ea9e0?, 0xc000aa50e0, 0x1, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/parsers.go:318 +0x30f
github.com/bishopfox/sliver/client/command/armory.fetchPackageSignature(0xc001012c70?, 0xa5ebe40, 0xc000aa50e0, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/armory.go:487 +0x3f4
created by github.com/bishopfox/sliver/client/command/armory.fetchPackageSignatures in goroutine 1
        github.com/bishopfox/sliver/client/command/armory/armory.go:445 +0x127

**Comment by mturhanlar** [comment]
I'm having same issue as well.

**Comment by moloch--** [comment]
Usually caused by internet connection problems, or Github has banned your IP from accessing the Github APIs for one reason or another.

**Comment by r00tVen0m** [comment]
i have this probleme

sliver > armory install all

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9d86a6]

goroutine 294 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, {0xc000a2ef60, 0x56}, 0xc0007925c9?)
        github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x166
github.com/bishopfox/sliver/client/command/armory.GithubArmoryPackageParser(0x1587a80?, 0xc0000a42d0, 0x1, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/parsers.go:318 +0x325
github.com/bishopfox/sliver/client/command/armory.fetchPackageSignature(0xc0009ee770?, 0x26d9480, 0xc0000a42d0, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/armory.go:487 +0x410
created by github.com/bishopfox/sliver/client/command/armory.fetchPackageSignatures
        github.com/bishopfox/sliver/client/command/armory/armory.go:450 +0x25e

**Comment by r00tVen0m** [comment]
sliver > armory install all

? Install 21 aliases and 141 extensions? Yes
[*] Installing alias 'SharpSecDump' (v0.0.1) ... done!
[*] Installing alias 'Rubeus' (v0.0.24) ... done!
[*] Installing alias 'SharpChrome' (v0.0.3) ... done!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9d86a6]

goroutine 1 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, {0xc0004923c0, 0x56}, 0x15?)
        github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x166
github.com/bishopfox/sliver/client/command/armory.GithubArmoryPackageParser(0x1587a80?, 0xc0013aedf0, 0x0, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/parsers.go:318 +0x325
github.com/bishopfox/sliver/client/command/armory.installAliasPackageByName({0xc00067ebf0?, 0x17debb4?}, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, 0x8d?)
        github.com/bishopfox/sliver/client/command/armory/install.go:146 +0x1bf
github.com/bishopfox/sliver/client/command/armory.installAlias(0xc00071a0d0, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, 0x267b2c8?)
        github.com/bishopfox/sliver/client/command/armory/install.go:116 +0x85
github.com/bishopfox/sliver/client/command/armory.installPackageByName({0xc000b4a288, 0x3}, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, 0x0?)
        github.com/bishopfox/sliver/client/command/armory/install.go:93 +0x145
github.com/bishopfox/sliver/client/command/armory.ArmoryInstallCmd(0xc0009a46a0, 0x0?)
        github.com/bishopfox/sliver/client/command/armory/install.go:64 +0x2f9
github.com/bishopfox/sliver/client/command.BindCommands.func14(0xc0008da900?)
        github.com/bishopfox/sliver/client/command/commands.go:247 +0x45
github.com/desertbit/grumble.(*App).RunCommand(0xc0004ca000, {0xc001714340?, 0x12?, 0x1bdd660?})
        github.com/desertbit/grumble@v1.1.1/app.go:273 +0x19f
github.com/desertbit/grumble.(*App).runShell(0xc0004ca000)
        github.com/desertbit/grumble@v1.1.1/app.go:485 +0x4c6
github.com/desertbit/grumble.(*App).RunWithReadline(0xc0004ca000, 0xc00043e750)
        github.com/desertbit/grumble@v1.1.1/app.go:407 +0x570
github.com/desertbit/grumble.(*App).Run(0xc0004ca000)
        github.com/desertbit/grumble@v1.1.1/app.go:291 +0x125
github.com/bishopfox/sliver/client/console.Start({0x1c51e48?, 0xc00033e110}, 0x1a55390, 0x1a54ca8, 0x0)
        github.com/bishopfox/sliver/client/console/console.go:145 +0x577
github.com/bishopfox/sliver/client/cli.StartClientConsole()
        github.com/bishopfox/sliver/client/cli/cli.go:100 +0x1a6
github.com/bishopfox/sliver/client/cli.glob..func1(0x2637ea0?, {0x175e673?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/client/cli/cli.go:74 +0x73
github.com/spf13/cobra.(*Command).execute(0x2637ea0, {0xc000040290, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2637ea0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/client/cli.Execute()
        github.com/bishopfox/sliver/client/cli/cli.go:105 +0x25
main.main()
        github.com/bishopfox/sliver/client/main.go:43 +0x17

**Comment by homelab192** [comment]
https://github.com/cobbr/Covenant/wiki/Installation-And-Startup

check this out easy to get running and learn

**Comment by sojubear** [comment]
had this issue, but was resolved after turning off my VPN
