### ISSUE TITLE
Server crashes in latest commit immediately on connect

### ISSUE THREAD

**Issue by jabedude** [BishopFox/sliver#241]
**Describe the bug**
Crashes immediately when implant connects to server. 

**To Reproduce**
1. Checkout latest commit: f5cbcea6f7493f887bcd772560ff1e3ea838fa54
2. Built and run server
3. Generate a linux ELF implant
4. Start listener and run implant

**Expected behavior**
Connection to succeed

**Backtrace**
```
sliver > mtls

[*] Starting mTLS listener ...
sliver >
[*] Successfully started job #1

sliver > generate -b -d -m 192.168.1.155 -o linux

[*] Generating new linux/amd64 implant binary
[*] Build completed in 00:00:05
[*] Implant saved to /home/sliver/SUCCESSFUL_SKULLDUGGERY

sliver > panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c8df1]

goroutine 73 [running]:
github.com/bishopfox/sliver/server/core.(*Session).ToProtobuf(0xc030632b00, 0xc0209dc620)
        github.com/bishopfox/sliver/server/core/sessions.go:86 +0x91
github.com/bishopfox/sliver/server/rpc.(*Server).Events(0xb458c10, 0xc00073cfc0, 0xae45940, 0xc0006ba700, 0x0, 0x0)
        github.com/bishopfox/sliver/server/rpc/rpc-events.go:37 +0x49e
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_Events_Handler(0x1000b00, 0xb458c10, 0xae439c0, 0xc00073cfa0, 0x1000b00, 0xb458c10)
        github.com/bishopfox/sliver/protobuf/rpcpb/services.pb.go:2160 +0x10b
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.PayloadStreamServerInterceptor.func1(0x1000b00, 0xb458c10, 0xae43960, 0xc00073cf80, 0xc00073cf00, 0xad39aa0, 0x1, 0xc00073cf80)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/logging/logrus/payload_interceptors.go:54 +0x158
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1000b00, 0xb458c10, 0xae43960, 0xc00073cf80, 0x17, 0xbfc618fb32eba41c)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.StreamServerInterceptor.func1(0x1000b00, 0xb458c10, 0xae43a20, 0xc000772440, 0xc00073cf00, 0xc00073cf20, 0xc0064f8501, 0xc000772440)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/logging/logrus/server_interceptors.go:65 +0x17a
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1000b00, 0xb458c10, 0xae43a20, 0xc000772440, 0x7f2622d88c28, 0x0)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware/tags.StreamServerInterceptor.func1(0x1000b00, 0xb458c10, 0xae43ba0, 0xc0007460c0, 0xc00073cf00, 0xc00073cf40, 0xc00073cf60, 0xc00073cf00)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/tags/interceptors.go:39 +0x250
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1000b00, 0xb458c10, 0xae43ba0, 0xc0007460c0, 0xc000146c68, 0x40e038)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x1000b00, 0xb458c10, 0xae43ba0, 0xc0007460c0, 0xc00073cf00, 0xad39aa0, 0xae3f300, 0xc000779710)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:58 +0xd1
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000304820, 0xae48fa0, 0xc0209d2000, 0xc0209e8200, 0xc0228144e0, 0xb409380, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.29.1/server.go:1336 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000304820, 0xae48fa0, 0xc0209d2000, 0xc0209e8200, 0x0)
        google.golang.org/grpc@v1.29.1/server.go:1409 +0xc5c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0209cc020, 0xc000304820, 0xae48fa0, 0xc0209d2000, 0xc0209e8200)
        google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Looks like a regresion introduced in commit `e03491141`, when calculating the reconnect time for the first time.

**Comment by rkervella** [comment]
Good catch. I just submitted a fix in #242 . Once the CI completes, I'll merge the fix.

**Comment by jabedude** [comment]
Awesome. @rkervella Sliver is a fantastic project! Thanks for the help

**Comment by rkervella** [comment]
No problem, this bug shouldn't have made it this far in the first place xD
