### ISSUE TITLE
mtls listener leaves hanging FDs

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#279]
**Describe the bug**
The mtls listener leaves file descriptors open even when they are not used by incoming slivers.  This eventually results in the ulimit being hit

**To Reproduce**
1. Start an mtls listener
2. Open a bunch of TCP connections to the socket
3. Eventually sliver stops accepting connections because it has too many open fds.  (1024 on most Linux defaults)

**Expected behavior**
Close sockets not being used.

**Comment by Matir** [comment]
Each one leaves a goroutine behind in this position:

```
goroutine 283 [chan receive, 4 minutes]:
github.com/bishopfox/sliver/server/c2.handleSliverConnection(0x1306e60, 0xc006136700)
	github.com/bishopfox/sliver/server/c2/tcp-mtls.go:125 +0x344
created by github.com/bishopfox/sliver/server/c2.acceptSliverConnections
	github.com/bishopfox/sliver/server/c2/tcp-mtls.go:82 +0x13a
```

**Comment by Matir** [comment]
In fact, it seems the `Send` chan on sessions is *never* closed at all.  Other transports don't use the same pattern of looping over the Send chan, so this is probably not an issue (though I haven't yet tested), but clearly blocks mtls.

My first thought is to close session.Send when a read error occurs (since we're never getting a response back from that session), but then we need to be careful with writes to the channel, as a write on a closed channel triggers a panic.

Alternatively, we add an mtls-specific channel in the handler (i.e., 'done') and when the read fails, we write to it, then transform the loop to select on both channels, and on a read from done, break the loop and allow the handler to exit.  However, in that case, since the `Send` chan is built without a capacity, we run the risk of commands blocking submission into the `Send` chan.
