### ISSUE TITLE
Event Broker Race

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#337]
**Describe the bug**

There appears to be a race in the event broker due to the gRPC server not quickly detecting a client disconnect from the Event stream, which triggers a send on closed channel since the deferred cleanup has not yet been called... or something like that.

**To Reproduce**

Trigger event quickly after gRPC stream client disconnect.

```
sliver > panic: send on closed channel

goroutine 8 [running]:
github.com/bishopfox/sliver/server/core.(*eventBroker).Start(0xc0003ae2d0)
        github.com/bishopfox/sliver/server/core/events.go:75 +0xcd
created by github.com/bishopfox/sliver/server/core.newBroker
        github.com/bishopfox/sliver/server/core/events.go:112 +0x145
```

**Comment by moloch--** [comment]
Fixed in `stage`
