### ISSUE TITLE
"fatal error: out of memory" when download a big file from implant

### ISSUE THREAD

**Issue by hayasec** [BishopFox/sliver#730]
**Describe the bug**
"fatal error: out of memory" when download a big file from implant

**To Reproduce**
1. use the target
2. download remote(40mb) local-path
3. sometimes crash

**Expected behavior**
2022/07/07 19:07:58 httpclient.go:265: Cancelling poll context
2022/07/07 19:07:58 sliver.go:212: [recv] sysHandler 7
2022/07/07 19:07:58 httpclient.go:618: [http] segments = [schema], filename = jquerys, ext = js
2022/07/07 19:07:58 httpclient.go:374: [http] GET -> https://192.168.28.1:443/schema/jquerys.js?a=8k8737300
2022/07/07 19:07:58 session.go:270: [http] send envelope ...
2022/07/07 19:08:00 httpclient.go:618: [http] segments = [v2 v2], filename = index, ext = jsp
2022/07/07 19:08:00 httpclient.go:265: Cancelling poll context
2022/07/07 19:08:00 httpclient.go:618: [http] segments = [], filename = jquerys, ext = js
2022/07/07 19:08:00 httpclient.go:374: [http] GET -> https://192.168.28.1:443/jquery.js?i=4851r5060
2022/07/07 19:08:03 httpclient.go:265: Cancelling poll context
2022/07/07 19:08:03 httpclient.go:618: [http] segments = [], filename = jquerys, ext = js
2022/07/07 19:08:03 httpclient.go:374: [http] GET -> https://192.168.28.1:443/jquery.js?d=2403a642t9
runtime: out of memory: cannot allocate 432013312-byte block (1039990784 in use)
fatal error: out of memory

goroutine 211 [running]:
runtime.throw({0x8f7442, 0xd})
        /usr/local/go/src/runtime/panic.go:992 +0x64 fp=0x130a3e10 sp=0x130a3dfc pc=0x4355f4
runtime.(*mcache).allocLarge(0x230088, 0x19be17f3, 0x1)
        /usr/local/go/src/runtime/mcache.go:215 +0x1d9 fp=0x130a3e38 sp=0x130a3e10 pc=0x414449
runtime.mallocgc(0x19be17f3, 0x87bd00, 0x1)
        /usr/local/go/src/runtime/malloc.go:1096 +0x446 fp=0x130a3e80 sp=0x130a3e38 pc=0x40b716
runtime.makeslice(0x87bd00, 0x0, 0x19be17f3)
        /usr/local/go/src/runtime/slice.go:103 +0x4f fp=0x130a3e94 sp=0x130a3e80 pc=0x4490af
strings.(*Builder).grow(...)
        /usr/local/go/src/strings/builder.go:67
strings.(*Builder).Grow(...)
        /usr/local/go/src/strings/builder.go:81
strings.Join({0x35000000, 0x2a45145, 0x2cd2800}, {0x9aa490, 0x1})
        /usr/local/go/src/strings/strings.go:438 +0xfb fp=0x130a3f00 sp=0x130a3e94 pc=0x4eaa4b
github.com/bishopfox/sliver/implant/sliver/encoders.English.Encode({}, {0x13600000, 0x2a45145, 0x2a45145})

**Desktop (please complete the following information):**
 - OS: server:ubuntu implant:windows 7
 - Version v1.5.17

**Comment by moloch--** [comment]
@RafBishopFox is working on a fix and some other updates to the file download functionality.

**Comment by hayasec** [comment]
same problem

**Comment by moloch--** [comment]
For now you have to breakup the file to download it.
