### ISSUE TITLE
Implant Crash on mTLS with Abrupt Server Termination

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#749]
The implant will occasionally crash if the server impolitely terminates the mtls connection in session mode:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10127f7fc]

goroutine 50 [running]:
github.com/bishopfox/sliver/implant/sliver/transports.(*Tunnel).Close(0x140000b7720)
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/tunnel.go:62 +0xac
github.com/bishopfox/sliver/implant/sliver/transports.(*Connection).removeAndCloseAllTunnels(0x140000960c0)
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/connection.go:80 +0x110
github.com/bishopfox/sliver/implant/sliver/transports.(*Connection).Cleanup.func1()
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/connection.go:48 +0x48
sync.(*Once).doSlow(0x14000090040, 0x140000f3e68)
	/Users/moloch/.sliver/go/src/sync/once.go:68 +0xf0
sync.(*Once).Do(0x14000090040, 0x140000f3e68)
	/Users/moloch/.sliver/go/src/sync/once.go:59 +0x48
github.com/bishopfox/sliver/implant/sliver/transports.(*Connection).Cleanup(0x140000960c0)
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/connection.go:45 +0x60
github.com/bishopfox/sliver/implant/sliver/transports.mtlsConnect.func3.2()
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/session.go:220 +0x128
created by github.com/bishopfox/sliver/implant/sliver/transports.mtlsConnect.func3
	/Users/moloch/.sliver/slivers/darwin/arm64/DISGUSTED_LOGIC/src/github.com/bishopfox/sliver/implant/sliver/transports/session.go:212 +0x43c
```

**Comment by moloch--** [comment]
Occurs in the tunnel clean up code, the but is only triggered when a tunnel was used during the session and wasn't cleaned up properly.
