### ISSUE TITLE
Remove credentials from loot but it crashed all of the sudden.

### ISSUE THREAD

**Issue by p3tr0v** [BishopFox/sliver#774]
**Describe the Bug**
Remove credentials from loot but it crashed all of the sudden.

```
[*] Server v1.5.16 - 23eef3d15cdc116a1b9936cf392fdade37d93ad4
[*] Welcome to the sliver shell, please type 'help' for options

[*] Check for updates with the 'update' command

sliver > loot rm

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc5487a]

goroutine 1 [running]:
github.com/bishopfox/sliver/client/command/loot.SelectLoot(0x0?, {0x19c95b0, 0xc0003a8130})
	github.com/bishopfox/sliver/client/command/loot/helpers.go:179 +0x27a
github.com/bishopfox/sliver/client/command/loot.LootRmCmd(0x122bb20?, 0xc0002b0100)
	github.com/bishopfox/sliver/client/command/loot/rm.go:29 +0x2d
github.com/bishopfox/sliver/client/command.BindCommands.func316(0xc00072d6e0?)
	github.com/bishopfox/sliver/client/command/commands.go:2942 +0x45
github.com/desertbit/grumble.(*App).RunCommand(0xc0003ac000, {0xc00063e040?, 0x7?, 0x1983720?})
	github.com/desertbit/grumble@v1.1.1/app.go:269 +0x19f
github.com/desertbit/grumble.(*App).runShell(0xc0003ac000)
	github.com/desertbit/grumble@v1.1.1/app.go:461 +0x4c6
github.com/desertbit/grumble.(*App).Run(0xc0003ac000)
	github.com/desertbit/grumble@v1.1.1/app.go:393 +0x53f
github.com/bishopfox/sliver/client/console.Start({0x19c95b0?, 0xc0003a8130}, 0x15477f8, 0x15471f8, 0x0)
	github.com/bishopfox/sliver/client/console/console.go:141 +0x517
github.com/bishopfox/sliver/client/cli.StartClientConsole()
	github.com/bishopfox/sliver/client/cli/cli.go:100 +0x1a6
github.com/bishopfox/sliver/client/cli.glob..func1(0x20bef20?, {0x127154d?, 0x0?, 0x0?})
	github.com/bishopfox/sliver/client/cli/cli.go:74 +0x76
github.com/spf13/cobra.(*Command).execute(0x20bef20, {0xc00003c340, 0x0, 0x0})
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x20bef20)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/bishopfox/sliver/client/cli.Execute()
	github.com/bishopfox/sliver/client/cli/cli.go:105 +0x25
main.main()
	github.com/bishopfox/sliver/client/main.go:43 +0x17
```

**To Reproduce**

**Expected behavior**
To remove any credentials from the loot

**Desktop (please complete the following information):**
OS: Kali Linux
Version 2022.2

**Comment by rkervella** [comment]
This has already been fixed in https://github.com/BishopFox/sliver/pull/760
The fix should be present in the latest releases.
