### ISSUE TITLE
Download file crash

### ISSUE THREAD

**Issue by CodeXTF2** [BishopFox/sliver#783]
```
sliver (PRIOR_MANOR) > panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xe40865]

goroutine 31 [running]:
github.com/bishopfox/sliver/client/command/filesystem.HandleDownloadResponse(0xc00035ecf0, 0xc000732500, 0x286000?)
        github.com/bishopfox/sliver/client/command/filesystem/download.go:158 +0x505
github.com/bishopfox/sliver/client/command/filesystem.DownloadCmd.func1(0xc00037e7c0?)
        github.com/bishopfox/sliver/client/command/filesystem/download.go:71 +0xec
github.com/bishopfox/sliver/client/console.(*SliverConsoleClient).triggerBeaconTaskCallback(0xc000520500, {0xc000638100, 0x76, 0x80})
        github.com/bishopfox/sliver/client/console/console.go:326 +0x42b
github.com/bishopfox/sliver/client/console.(*SliverConsoleClient).EventLoop(0xc000520500)
        github.com/bishopfox/sliver/client/console/console.go:251 +0xf73
created by github.com/bishopfox/sliver/client/console.Start
        github.com/bishopfox/sliver/client/console/console.go:139 +0x4d6
```
was trying to download a folder and it crashed. Just throwing this here in case it hasnt already been reported.
edit: this was from a beacon. the same folder over a session could be downloaded iirc.

**Comment by CodeXTF2** [comment]
folder contents:
```
c:\users\public\results (19 items, 7.1 MiB)
===========================================
-rw-rw-rw-  chrome_default_bookmark.csv                2.8 KiB    Thu Aug 11 01:46:13 +0800 2022
-rw-rw-rw-  chrome_default_download.csv                893.7 KiB  Thu Aug 11 01:46:13 +0800 2022
-rw-rw-rw-  chrome_default_extension.csv               1.6 KiB    Thu Aug 11 01:46:13 +0800 2022
-rw-rw-rw-  chrome_default_history.csv                 5.2 MiB    Thu Aug 11 01:46:13 +0800 2022
-rw-rw-rw-  chrome_default_password.csv                24.7 KiB   Thu Aug 11 01:46:13 +0800 2022
-rw-rw-rw-  chrome_network_cookie.csv                  337.4 KiB  Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_bookmark.csv      609 B      Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_cookie.csv        163.9 KiB  Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_download.csv      707 B      Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_extension.csv     1.4 KiB    Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_history.csv       124.2 KiB  Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_localstorage.csv  335.0 KiB  Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  firefox_f1rts5jp_default_password.csv      782 B      Thu Aug 11 01:46:14 +0800 2022
-rw-rw-rw-  microsoft_edge_default_bookmark.csv        2.4 KiB    Thu Aug 11 01:46:12 +0800 2022
-rw-rw-rw-  microsoft_edge_default_download.csv        916 B      Thu Aug 11 01:46:12 +0800 2022
-rw-rw-rw-  microsoft_edge_default_history.csv         22.5 KiB   Thu Aug 11 01:46:12 +0800 2022
-rw-rw-rw-  microsoft_edge_default_localstorage.csv    22.5 KiB   Thu Aug 11 01:46:12 +0800 2022
-rw-rw-rw-  microsoft_edge_default_password.csv        127 B      Thu Aug 11 01:46:12 +0800 2022
-rw-rw-rw-  microsoft_edge_network_cookie.csv          29.9 KiB   Thu Aug 11 01:46:12 +0800 2022
```
