### ISSUE TITLE
DNS Rebind Crash

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#79]
```
goroutine 65 [running]:                                                                                          
sliver/server/c2.dnsSessionPoll(0xc00b9455f0, 0x8, 0xc00bb523c0, 0x3, 0x3, 0x2, 0xc00bb523c0, 0x3, 0x3, 0xb458e0)
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:624 +0x109                                              
sliver/server/c2.handleTXT(0xc00b9455f0, 0x8, 0xc00058a360, 0x18, 0xc00bb50120, 0x1)                             
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:301 +0xd62                                              
sliver/server/c2.handleC2(0xc00b9455f0, 0x8, 0xc00bb50120, 0x23)                                                 
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:171 +0x182                                              
sliver/server/c2.handleDNSRequest(0xc00b5e5d70, 0x1, 0x1, 0x1, 0x9f48200, 0xc00bb00680, 0xc00bb50120)            
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:136 +0x1b8                                              
sliver/server/c2.StartDNSListener.func1(0x9f48200, 0xc00bb00680, 0xc00bb50120)                                   
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:113 +0xc7                                               
sliver/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00bb54060, 0x9f48200, 0xc00bb00680, 0xc00bb50120)     
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:52 +0x44                               
sliver/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00000de60, 0x9f48200, 0xc00bb00680, 0xc00bb50120)     
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/serve_mux.go:128 +0x5d                           
sliver/vendor/github.com/miekg/dns.(*Server).serveDNS(0xc00001de00, 0xc00bb00680)                                
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:687 +0x298                             
sliver/vendor/github.com/miekg/dns.(*Server).serve(0xc00001de00, 0xc00bb00680)                                   
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:572 +0x2bc                             
sliver/vendor/github.com/miekg/dns.(*Server).worker(0xc00001de00, 0xc00bb00680)                                  
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:244 +0x4d                              
created by sliver/vendor/github.com/miekg/dns.(*Server).spawnWorker                                              
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:284 +0x83
```

**Comment by rkervella** [comment]
Fixed in #403
