### ISSUE TITLE
Execute-assembly crashed sliver-client with panic: failed to assert flag 'ppid' to int

### ISSUE THREAD

**Issue by akmalhisyam** [BishopFox/sliver#801]
**Describe the bug**
Execute-assembly caused sliver-client to crash with `panic: failed to assert flag 'ppid' to int`

**To Reproduce**
```
sliver (beacon) > version

[*] Client v1.5.23 - 79f2d48fcdfc2bee4713b78d431ea4b27f733f30 - linux/amd64
    Compiled at 2022-08-24 20:51:58 +0000 UTC
    Compiled with go version go1.18.5 linux/amd64


[*] Server v1.5.23 - 79f2d48fcdfc2bee4713b78d431ea4b27f733f30 - linux/amd64
    Compiled at 2022-08-24 20:51:57 +0000 UTC

sliver (beacon) > execute-assembly portscanner.exe 8.8.8.8

panic: failed to assert flag 'ppid' to int

goroutine 1 [running]:
github.com/desertbit/grumble.FlagMap.Int(0xc000160480?, {0x1279579, 0x4})
        github.com/desertbit/grumble@v1.1.1/flagmap.go:90 +0xb3
github.com/bishopfox/sliver/client/command/exec.ExecuteAssemblyCmd(0xc00058e680, 0xc00058ab80)
        github.com/bishopfox/sliver/client/command/exec/execute-assembly.go:78 +0x40d
github.com/bishopfox/sliver/client/command.BindCommands.func102(0xc0002d2420?)
        github.com/bishopfox/sliver/client/command/commands.go:1073 +0x45
github.com/desertbit/grumble.(*App).RunCommand(0xc0005d2700, {0xc00058bdc0?, 0x2e?, 0x198d090?})
        github.com/desertbit/grumble@v1.1.1/app.go:273 +0x19f
github.com/desertbit/grumble.(*App).runShell(0xc0005d2700)
        github.com/desertbit/grumble@v1.1.1/app.go:485 +0x4c6
github.com/desertbit/grumble.(*App).RunWithReadline(0xc0005d2700, 0xc00000efd8)
        github.com/desertbit/grumble@v1.1.1/app.go:407 +0x53f
github.com/desertbit/grumble.(*App).Run(0xc0005d2700)
        github.com/desertbit/grumble@v1.1.1/app.go:291 +0x11a
github.com/bishopfox/sliver/client/console.Start({0x19d54f0?, 0xc00047f5f0}, 0x1550668, 0x1550058, 0x0)
        github.com/bishopfox/sliver/client/console/console.go:142 +0x537
github.com/bishopfox/sliver/client/cli.StartClientConsole()
        github.com/bishopfox/sliver/client/cli/cli.go:100 +0x1a6
github.com/bishopfox/sliver/client/cli.glob..func1(0x20ccf20?, {0x12790f1?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/client/cli/cli.go:74 +0x76
github.com/spf13/cobra.(*Command).execute(0x20ccf20, {0xc00003c330, 0x0, 0x0})
        github.com/spf13/cobra@v1.1.1/command.go:854 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x20ccf20)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/bishopfox/sliver/client/cli.Execute()
        github.com/bishopfox/sliver/client/cli/cli.go:105 +0x25
main.main()
        github.com/bishopfox/sliver/client/main.go:43 +0x17
```

**Comment by rkervella** [comment]
My bad, made a typo in the flag type for this specific command. All the other commands are fine (double checked today). Fix is on its way.

**Comment by rkervella** [comment]
Release v1.5.24 includes the fix
