### ISSUE TITLE
Nil Pointer Deref on DNS Session Resume

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#82]
If a sliver server restarts and an implant is in the middle of an existing session the poll request with a no-longer valid DNS Session ID will trigger a nil pointer deref:

```
 panic: runtime error: invalid memory address or nil pointer dereference                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x98cf69]                                          
                                                                                                    
goroutine 54 [running]:                                                                                          
sliver/server/c2.dnsSessionPoll(0xc000093fc0, 0x8, 0xc00bba7350, 0x3, 0x3, 0x2, 0xc00bba7350, 0x3, 0x3, 0xb45960)
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:624 +0x109                                              
sliver/server/c2.handleTXT(0xc000093fc0, 0x8, 0xc0005c9e60, 0x18, 0xc00bb0a5a0, 0x1)                             
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:301 +0xd62                                              
sliver/server/c2.handleC2(0xc000093fc0, 0x8, 0xc00bb0a5a0, 0x23)                                                 
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:171 +0x182                                              
sliver/server/c2.handleDNSRequest(0xc00007fb20, 0x1, 0x1, 0x1, 0x9f483e0, 0xc00bac0b00, 0xc00bb0a5a0)            
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:136 +0x1b8                                              
sliver/server/c2.StartDNSListener.func1(0x9f483e0, 0xc00bac0b00, 0xc00bb0a5a0)                                   
        /Users/moloch/go/src/sliver/server/c2/udp-dns.go:113 +0xc7                                               
sliver/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00bba6090, 0x9f483e0, 0xc00bac0b00, 0xc00bb0a5a0)     
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:52 +0x44                               
sliver/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00000dee0, 0x9f483e0, 0xc00bac0b00, 0xc00bb0a5a0)     
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/serve_mux.go:128 +0x5d                           
sliver/vendor/github.com/miekg/dns.(*Server).serveDNS(0xc00baca900, 0xc00bac0b00)                                
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:687 +0x298                             
sliver/vendor/github.com/miekg/dns.(*Server).serve(0xc00baca900, 0xc00bac0b00)                                   
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:572 +0x2bc                             
sliver/vendor/github.com/miekg/dns.(*Server).worker(0xc00baca900, 0xc000013400)                                  
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:269 +0x1bf                             
created by sliver/vendor/github.com/miekg/dns.(*Server).spawnWorker                                              
        /Users/moloch/go/src/sliver/vendor/github.com/miekg/dns/server.go:284 +0x83
```

**Comment by rkervella** [comment]
Fixed in #403
