### ISSUE TITLE
Beacons Segfault Amid Connectivity Issues

### ISSUE THREAD

**Issue by pb376** [BishopFox/sliver#919]
Our server had six active beacons that had been generated with:

`generate beacon --mtls $IP:$PORT --os linux --max-errors 1000000 --save /opt/agents/`

The server was installed yesterday and is running the latest release, v1.5.27.

Server connectivity issues began last night, which resulted in four of the six implants dying. The beacons had been started at different times so their checkin times were not aligned, as one would expect. Interestingly their last checkin time recorded before dying was Wed Sep 28 13:05:10 for all four beacons, though I would guess that is just related to the connectivity issues resolving and hanging connections continuing to be processed.

Checking the boxes the agents were running on, each had the same error printed:

```
goroutine 273 [running]:             
G71ebhNV.(*K7ZYzL0g).Close(0x0)
        JgdIXW4y.go:1 +0x24
QC8XO3rP.gEa7seBz.func5()                                   
        IQE5Jgnz.go:1 +0x32                                                                                              
main.zeBVuxjm.func1()
        XVQzCwek.go:1 +0x35                                
main.zeBVuxjm(0xc0000ce2d0, {0x0?, 0x0?, 0x0?})
        DEkOltFc.go:2 +0x316            
main.cm6jKUfu.func2()                                     
        TzA_GlBp.go:1 +0x67                                                       
created by main.cm6jKUfu                                                                      
        Ab6yXSvm.go:2 +0x555 
```

**Comment by pb376** [comment]
I was just able to recreate the issue, this time using a debug build without symbol obfuscation, by reducing the beacon and reconnect intervals and repeatedly simulating abrupt loss of connectivity to the server. The error printed is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75d72a]

goroutine 77 [running]:
crypto/tls.(*Conn).Close(0x0)
        /root/.sliver/go/src/crypto/tls/conn.go:1319 +0x4a
github.com/bishopfox/sliver/implant/sliver/transports.mtlsBeacon.func5()
        /root/.sliver/slivers/linux/amd64/debug2/src/github.com/bishopfox/sliver/implant/sliver/transports/beacon.go:196 +0x3d
main.beaconMain.func1()
        /root/.sliver/slivers/linux/amd64/debug2/src/github.com/bishopfox/sliver/sliver.go:237 +0x50
main.beaconMain(0xc0003c14a0, {0xc0c542bc1bc5ff20, 0x10d33136413, 0xdb6500})
        /root/.sliver/slivers/linux/amd64/debug2/src/github.com/bishopfox/sliver/sliver.go:281 +0x90d
main.beaconMainLoop.func2()
        /root/.sliver/slivers/linux/amd64/debug2/src/github.com/bishopfox/sliver/sliver.go:196 +0x76
created by main.beaconMainLoop
        /root/.sliver/slivers/linux/amd64/debug2/src/github.com/bishopfox/sliver/sliver.go:194 +0x816
```

Looking at `sliver/implant/sliver/transports/beacon.go` on the server, line 196 is `err = conn.Close()` found [here](https://github.com/BishopFox/sliver/blob/11949202b581b843160801a232dc61e1afa39cc1/implant/sliver/transports/beacon.go#L214). Do we just need to check if conn is nil before attempting to close?
